; GoldLogic OA 容器 PHP 附加配置
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 120
memory_limit = 512M
date.timezone = Asia/Shanghai
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
session.save_handler = files